services:
  app:
    build:
      context: .
    ports:
      - "80:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: financial_db
      DB_PORT: 3306
      PORT: 3000
    command: npm start
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: financial_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

